### ISSUE TITLE
add new resource warning

### ISSUE THREAD

**Issue by mydearxym** [note89/phoenix-hipster-stack#3]
thanks for the work!
a error msg shows in the console when i add a new resource

![image](https://cloud.githubusercontent.com/assets/6184465/14461017/4ad7e080-00f3-11e6-91e8-f27294e0378b.png)

``` js
warning.js?8a56:44 Warning: writeRelayUpdatePayload(): Expected response payload to include the newly created edge `linkEdge` and its `node` field. Did you forget to update the `RANGE_ADD` mutation config?
```

**Comment by note89** [comment]
Yes that is also present in the original repo that i ported. http://rgrjs.com/.
I have not looked into a solution yet. Am working hard on a Elm version on this repo instead :)
But if you find a solution be sure to let me know

**Comment by note89** [comment]
close since its is just a warning and also pressent in the repo from where this is inpired from.
