### ISSUE TITLE
Query example in Readme

### ISSUE THREAD

**Issue by puruzio** [note89/phoenix-hipster-stack#4]
The query example says the following but these are not the fields in the linkConnection (title, url, etc.)

query myQuery{
  store{
    authors {
      id
      name
    }
  }
}

I think the right query would be more like this, but it doesn't return anything. What am I missing?

query myQuery{
  store{
    id,
    linkConnection(first:5) {
     edges {
        cursor,
        node {
          id,
          title,
          url,
          createdAt
        }
      }
      pageInfo {
        hasNextPage
      }
    }
  }
}

**Comment by note89** [comment]
You need to query for something

```
query derp{
  store{
    linkConnection(query:"") {
      edges {
        node {
          id
          title
          url
        }
      }
    }
  }
}
```
