### ISSUE TITLE
Isn't Elm pretty hipster?

### ISSUE THREAD

**Issue by hsavit1** [note89/phoenix-hipster-stack#5]
Care to make an example using Elm?

**Comment by hsavit1** [comment]
Also the example app is broken

**Comment by note89** [comment]
That is why we also built this.
https://github.com/carleryd/elm-hipster-stack

**Comment by note89** [comment]
What is broken ?

**Comment by hsavit1** [comment]
Oh great! 

When you click on the SAMPLE APP link in the README, it directs me to a page showing 502 bad gateway

**Comment by note89** [comment]
I removed the link, to lazy to start the docker container again XD
