### ISSUE TITLE
BadFunctionError on submission of new link

### ISSUE THREAD

**Issue by JoeIaquinto** [note89/phoenix-hipster-stack#6]
I cloned the project installed the dependencies as instructed. When I add a link through the 'Add New Resource' form there is a server error from the POST request on /graphql. 

    ** (BadFunctionError) expected a function, got: {App.PublicSchema, :mutate_and_get_payload}

        lib/graphql/relay/mutation.ex:48: anonymous fn/4 in GraphQL.Relay.Mutation.new/1

        (graphql) lib/graphql/execution/executor.ex:168: GraphQL.Execution.Executor.resolve_field/4

        (graphql) lib/graphql/execution/executor.ex:127: anonymous fn/5 in GraphQL.Execution.Executor.execute_fields/4

        (stdlib) lists.erl:1262: :lists.foldl/3

        (graphql) lib/graphql/execution/executor.ex:86: GraphQL.Execution.Executor.execute_operation/3

        (graphql) lib/graphql.ex:25: GraphQL.execute/5

        (plug_graphql) lib/graphql/plug/endpoint.ex:85: GraphQL.Plug.Endpoint.execute/2

        (plug_graphql) lib/graphql/plug.ex:54: GraphQL.Plug.call/2

Any ideas on something i've got mixed up here? Can you reproduce this on a clean build?

**Comment by note89** [comment]
Sorry for the late reply, forgot to take a look at it. 
See if it works better now.

**Comment by JoeIaquinto** [comment]
Looks like ce2ca7dda9b79a63fcb38c8b734ebd5849323799 fixed it! Posting links and adjusting # of links viewed is responsive to input. I have noticed that my RethinkDB console isn't seeing any reads/ writes when I'm testing. Is this currently unimplemented and just uses a local store from /web/graphql/types/store?

**Comment by JoeIaquinto** [comment]
Should this function format be adopted for other sections like the link.ex queries and type definitions? I could write up a quick PR if so, I'd like to help out.
